[program:phoenixd]
command=/phoenix/phoenixd
    --agree-to-terms-of-service
    --chain=%(ENV_PHOENIXD_NETWORK)s
    --auto-liquidity=5m
    --max-mining-fee=50000
    --max-fee-credit=50k
    --max-relative-fee-percent=40
    --http-password=%(ENV_PHOENIXD_API_PASSWORD)s
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/phoenixd.log
stderr_logfile=/var/log/supervisor/phoenixd_err.log
user=root
environment=PATH="/app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",PHOENIXD_API_PASSWORD=%(ENV_PHOENIXD_API_PASSWORD)s,PHOENIXD_NETWORK=%(ENV_PHOENIXD_NETWORK)s